import PyPDF2
pdfFileObj = open('jerin.pdf', 'rb')
pdfReader = PyPDF2.PdfFileReader(pdfFileObj)
pageObjpdf = pdfReader.getPage(0)
cc = open('watermark.pdf', 'rb')
page = PyPDF2.PdfFileReader(pdfFileObj)
pagewater = pdfReader.getPage(0)
pageObjpdf.mergePage(pagewater)
vv=PyPDF2.PdfFileWriter()
vv.addPage(pageObjpdf)
merged_file = open('merged_file','wb')
vv.write(merged_file)
merged_file.close()
cc.close()
pdfFileObj.close()